# Generated by Django 4.2.11 on 2026-01-29 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(
                    choices=[('openai', 'OpenAI'), ('zhipuai', '智谱AI ZhipuAI'), ('qwen', '阿里通义千问 Qwen'), ('other', '其他')],
                    default='openai',
                    max_length=50
                )),
                ('model_name', models.CharField(
                    help_text="Model identifier (e.g., 'gpt-4o-mini', 'glm-4-flash')",
                    max_length=100
                )),
                ('api_key_encrypted', models.TextField(
                    blank=True,
                    help_text='Encrypted API key'
                )),
                ('base_url', models.URLField(
                    blank=True,
                    help_text='Custom base URL for API (optional)',
                    max_length=500
                )),
                ('max_tokens', models.IntegerField(
                    default=2000,
                    help_text='Maximum tokens in LLM response'
                )),
                ('temperature', models.FloatField(
                    default=0.7,
                    help_text='Temperature for text generation (0.0-2.0)'
                )),
                ('model_params', models.JSONField(
                    blank=True,
                    default=dict,
                    help_text='Additional model parameters'
                )),
                ('is_active', models.BooleanField(
                    default=True,
                    help_text='Whether this configuration is active'
                )),
                ('is_default', models.BooleanField(
                    default=False,
                    help_text='Whether this is the default configuration'
                )),
            ],
            options={
                'verbose_name': 'LLM Model Config',
                'verbose_name_plural': 'LLM Model Configs',
                'db_table': 'llm_model_configs',
                'ordering': ['-is_default', 'provider', 'model_name'],
            },
        ),
    ]
