# Generated by Django 4.2.11 on 2026-01-29 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_capabilityrequirement_title'),
        ('products', '0004_alter_feature_options_alter_product_options'),
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(db_index=True, help_text='SHA-256 hash of the input parameters', max_length=64, unique=True)),
                ('requirement_text', models.TextField(help_text='The requirement text that was analyzed')),
                ('feature_ids', models.JSONField(help_text='List of feature IDs that were analyzed')),
                ('response_json', models.JSONField(help_text='Cached LLM response')),
                ('hit_count', models.IntegerField(default=0, help_text='Number of times this cache entry has been used')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cache entry should expire')),
                ('llm_provider', models.CharField(help_text='Provider that generated this response', max_length=50)),
                ('llm_model', models.CharField(help_text='Model that generated this response', max_length=100)),
            ],
            options={
                'verbose_name': 'LLM Cache',
                'verbose_name_plural': 'LLM Cache',
                'db_table': 'llm_cache',
                'ordering': ['-hit_count', '-created_at'],
                'indexes': [models.Index(fields=['cache_key'], name='llm_cache_cache_k_c17b9e_idx'), models.Index(fields=['expires_at'], name='llm_cache_expires_fde34c_idx'), models.Index(fields=['llm_provider', 'llm_model'], name='llm_cache_llm_pro_6de9c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_reason', models.TextField(blank=True, help_text="LLM's reasoning for the match decision")),
                ('keywords_from_requirement', models.JSONField(blank=True, default=list, help_text='Key phrases extracted from requirement')),
                ('keywords_from_feature', models.JSONField(blank=True, default=list, help_text='Key phrases extracted from feature')),
                ('is_valid_match', models.BooleanField(help_text="LLM's judgment on whether this is a valid match", null=True)),
                ('confidence_score', models.FloatField(help_text="LLM's confidence score (0.0-1.0)", null=True)),
                ('llm_provider', models.CharField(help_text="Provider used for analysis (e.g., 'openai', 'zhipuai')", max_length=50)),
                ('llm_model', models.CharField(help_text="Model used for analysis (e.g., 'gpt-4o-mini')", max_length=100)),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='Number of tokens in the prompt', null=True)),
                ('completion_tokens', models.IntegerField(blank=True, help_text='Number of tokens in the completion', null=True)),
                ('total_tokens', models.IntegerField(blank=True, help_text='Total tokens used (prompt + completion)', null=True)),
                ('analysis_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from the analysis')),
                ('feature', models.ForeignKey(help_text='The feature being compared', on_delete=django.db.models.deletion.CASCADE, related_name='llm_analyses', to='products.feature')),
                ('requirement_item', models.ForeignKey(help_text='The requirement item being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='llm_analyses', to='matching.requirementitem')),
            ],
            options={
                'verbose_name': 'LLM Analysis Result',
                'verbose_name_plural': 'LLM Analysis Results',
                'db_table': 'llm_analysis_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requirement_item', 'feature'], name='llm_analysi_require_6ab2c5_idx'), models.Index(fields=['llm_provider', 'llm_model'], name='llm_analysi_llm_pro_5896a7_idx'), models.Index(fields=['is_valid_match'], name='llm_analysi_is_vali_52f6d9_idx'), models.Index(fields=['confidence_score'], name='llm_analysi_confide_c34351_idx')],
                'unique_together': {('requirement_item', 'feature')},
            },
        ),
    ]
