# Generated by Django 4.2.11 on 2026-01-29 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_llmcache_llmanalysisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmanalysisresult',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text="LLM's confidence score (0.0-1.0)", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='llmanalysisresult',
            name='is_valid_match',
            field=models.BooleanField(blank=True, help_text='LLM judgment: True=valid, False=invalid, Null=not analyzed or inconclusive', null=True),
        ),
    ]
