# Generated by Django 4.2.11 on 2026-01-30 02:11

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_alter_llmanalysisresult_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('REQUEST_ID', models.CharField(db_index=True, help_text='Unique request identifier (UUID)', max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the request was made')),
                ('provider', models.CharField(db_index=True, help_text="LLM provider (e.g., 'openai', 'zhipuai')", max_length=50)),
                ('model', models.CharField(db_index=True, help_text="Model name (e.g., 'gpt-4o-mini', 'glm-4-flash')", max_length=100)),
                ('prompt_tokens', models.IntegerField(help_text='Number of tokens in the prompt', validators=[django.core.validators.MinValueValidator(0)])),
                ('completion_tokens', models.IntegerField(help_text='Number of tokens in the completion', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tokens', models.IntegerField(help_text='Total tokens used', validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_usd', models.FloatField(help_text='Estimated cost in USD', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('request_type', models.CharField(help_text="Type of request (e.g., 'analysis', 'batch_analysis', 'keyword_extraction')", max_length=50)),
                ('requirement_id', models.CharField(blank=True, db_index=True, help_text='Associated requirement ID (if applicable)', max_length=100, null=True)),
                ('feature_count', models.IntegerField(default=1, help_text='Number of features analyzed', validators=[django.core.validators.MinValueValidator(0)])),
                ('cache_hit', models.BooleanField(default=False, help_text='Whether result came from cache')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('success', '成功'), ('error', '错误'), ('timeout', '超时')], default='success', help_text='Request status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (config_id, mode, etc.)')),
            ],
            options={
                'verbose_name': 'LLM Usage Log',
                'verbose_name_plural': 'LLM Usage Logs',
                'db_table': 'llm_usage_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='llm_usage_l_timesta_509137_idx'), models.Index(fields=['provider', 'model'], name='llm_usage_l_provide_d0ddce_idx'), models.Index(fields=['request_type'], name='llm_usage_l_request_aef2f0_idx'), models.Index(fields=['requirement_id'], name='llm_usage_l_require_564e9b_idx'), models.Index(fields=['status'], name='llm_usage_l_status_4f25a2_idx'), models.Index(fields=['cache_hit'], name='llm_usage_l_cache_h_6ecf2a_idx')],
            },
        ),
    ]
