# Generated by Django 6.0.1 on 2026-01-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_llmusagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodelconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('zhipuai', '智谱AI ZhipuAI'), ('qwen', '阿里通义千问 Qwen'), ('siliconflow', '硅基流动 SiliconFlow'), ('other', '其他')], default='openai', max_length=50),
        ),
    ]
