# Generated by Django 6.0.1 on 2026-01-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_alter_llmmodelconfig_provider'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='llmmodelconfig',
            constraint=models.UniqueConstraint(fields=('provider', 'model_name'), name='unique_provider_model'),
        ),
    ]
