# Generated by Django 4.2.11 on 2026-01-09 06:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(db_index=True)),
                ('requirement_text', models.TextField(blank=True)),
                ('requirement_type', models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=20)),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Capability Requirement',
                'verbose_name_plural': 'Capability Requirements',
                'db_table': 'capability_requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_text', models.TextField()),
                ('item_order', models.IntegerField(default=0)),
                ('embedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.featureembedding')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='matching.capabilityrequirement')),
            ],
            options={
                'verbose_name': 'Requirement Item',
                'verbose_name_plural': 'Requirement Items',
                'db_table': 'requirement_items',
                'ordering': ['requirement', 'item_order'],
            },
        ),
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similarity_score', models.FloatField(db_index=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('partial_matched', 'Partial Matched'), ('unmatched', 'Unmatched')], max_length=20)),
                ('threshold_used', models.FloatField()),
                ('rank', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='products.feature')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matching.capabilityrequirement')),
                ('requirement_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matching.requirementitem')),
            ],
            options={
                'verbose_name': 'Match Record',
                'verbose_name_plural': 'Match Records',
                'db_table': 'match_records',
                'ordering': ['-similarity_score'],
            },
        ),
    ]
