# Generated by Django 4.2.11 on 2026-01-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityrequirement',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='需求名称'),
        ),
    ]
