# Generated by Django 4.2.11 on 2026-01-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_llmcache_llmanalysisresult'),
        ('matching', '0002_capabilityrequirement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecord',
            name='final_confidence',
            field=models.FloatField(blank=True, db_index=True, help_text='Final confidence score after LLM correction (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='is_llm_corrected',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the match status was corrected by LLM analysis'),
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='llm_analysis',
            field=models.ForeignKey(blank=True, help_text='Link to LLM analysis if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_records', to='llm.llmanalysisresult'),
        ),
        migrations.AddIndex(
            model_name='matchrecord',
            index=models.Index(fields=['is_llm_corrected'], name='match_recor_is_llm__8651e5_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrecord',
            index=models.Index(fields=['final_confidence'], name='match_recor_final_c_f9e27a_idx'),
        ),
    ]
