# Generated by Django 4.2.11 on 2026-01-29 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_matchrecord_final_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecord',
            name='original_match_status',
            field=models.CharField(blank=True, choices=[('matched', 'Matched'), ('partial_matched', 'Partial Matched'), ('unmatched', 'Unmatched')], help_text='Match status before LLM correction', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchrecord',
            name='final_confidence',
            field=models.FloatField(blank=True, db_index=True, help_text='Final confidence score after LLM correction (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
