# Generated by Django 4.2.11 on 2026-01-09 06:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('feature_name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('importance_level', models.IntegerField(default=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'features',
                'ordering': ['category', 'subcategory', 'feature_name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.JSONField(default=list)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='products.feature')),
            ],
            options={
                'verbose_name': 'Feature Embedding',
                'verbose_name_plural': 'Feature Embeddings',
                'db_table': 'feature_embeddings',
                'indexes': [models.Index(fields=['model_name'], name='feature_emb_model_n_29fd9d_idx')],
                'unique_together': {('feature', 'model_name')},
            },
        ),
    ]
