# Generated by Django 4.2.11 on 2026-01-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
