# Generated by Django 4.2.11 on 2026-01-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_subsystem_and_hierarchy_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['level1_function', 'level2_function', 'feature_name'], 'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['subsystem_type', '-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
