# Generated by Django 6.0.1 on 2026-02-01 03:37

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_feature_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
