# Generated by Django 4.2.11 on 2026-01-09 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'HuggingFace'), ('sentence-transformers', 'Sentence-Transformers'), ('local', 'Local Model')], max_length=50)),
                ('provider', models.CharField(max_length=100)),
                ('api_endpoint', models.CharField(blank=True, max_length=500)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('dimension', models.IntegerField()),
                ('model_params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Embedding Model Config',
                'verbose_name_plural': 'Embedding Model Configs',
                'db_table': 'embedding_model_configs',
                'ordering': ['-is_default', 'model_name'],
            },
        ),
    ]
