# Generated by Django 4.2.11 on 2026-01-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingmodelconfig',
            name='base_url',
            field=models.URLField(blank=True, help_text='API基础URL（用于OpenAI-compatible类型）', max_length=500),
        ),
        migrations.AddField(
            model_name='embeddingmodelconfig',
            name='provider_name',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('siliconflow', '硅基流动 SiliconFlow'), ('zhipuai', '智谱AI ZhipuAI'), ('qwen', '阿里通义千问 Qwen'), ('sentence-transformers', 'Sentence-Transformers'), ('other', '其他')], default='other', help_text='API提供商名称（用于OpenAI-compatible类型）', max_length=100),
        ),
        migrations.AlterField(
            model_name='embeddingmodelconfig',
            name='model_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'HuggingFace'), ('sentence-transformers', 'Sentence-Transformers'), ('local', 'Local Model'), ('openai-compatible', 'OpenAI-Compatible (硅基流动/智谱/通义等)')], max_length=50),
        ),
    ]
